bifrost:
  big-bang:
    type: public
    genesis-id: b_92C9DZbbMe2uCvnrjnNjvWTFzSpEWDxmzkGK56vpg84n
    source-path: https://raw.githubusercontent.com/Topl/Genesis_Testnets/testnet-topl-co/testnet-topl-co
  p2p:
    network-properties:
      expected-slots-per-block: 20
  protocols:
    0:
      epoch-length-override: 6000
