bifrost:
  big-bang:
    type: public
    genesis-id: b_HhhpNduPPRwxR8wKez4uSRMF75ovzDPEuWHN5J6Vrfva
    source-path: https://raw.githubusercontent.com/Topl/Genesis_Testnets/BN-1425-update-testnet-topl-co-to-use-multi-node-setup/testnet-topl-co
  p2p:
    network-properties:
      expected-slots-per-block: 10
