bifrost:
  big-bang:
    type: public
    genesis-id: b_E86F5tt19st1Xvu3Gsyb7wNcsiSE4yK2NAdUdtRk2gbA
    source-path: https://raw.githubusercontent.com/Topl/Genesis_Testnets/update-dev-testnet/testnet3
