bifrost:
  big-bang:
    type: public
    genesis-id: b_FbRLB68FoRrtnFxrDDa7u8PEUroFbXnJLdPXiQ1e45v
    source-path: https://raw.githubusercontent.com/Topl/Genesis_Testnets/update-dev-testnet/testnet3
