bifrost:
  big-bang:
    type: public
    genesis-id: b_9MCCshXRyRPrT9uZMPfUBV3d1fctZyF5Pk6AmciRpYiw
    source-path: https://raw.githubusercontent.com/Topl/Genesis_Testnets/update-dev-testnet/testnet3
  p2p:
    network-properties:
      expected-slots-per-block: 20
  protocols:
    0:
      epoch-length-override: 3000
