bifrost:
  big-bang:
    type: public
    genesis-id: b_BJp2boSCGxFMf5Q72f5RF2Wvd18mMUBcx6t6KteUqQtE
    source-path: https://raw.githubusercontent.com/Topl/Genesis_Testnets/update-dev-testnet/testnet3
  p2p:
    network-properties:
      expected-slots-per-block: 10
