bifrost:
  big-bang:
    type: public
    genesis-id: b_CmbkdPSr8aqrvGeLD9NZL5Kza3rGAz5RWGL85s8QzuQe
    source-path: https://raw.githubusercontent.com/Topl/Genesis_Testnets/update-during-epoch/openstack-test
