bifrost:
  big-bang:
    type: public
    genesis-id: b_dTMdNhPGERFft8XPspnowYEkCXXDcAkH5To119LCdkh
    source-path: https://raw.githubusercontent.com/Topl/Genesis_Testnets/update-during-epoch/openstack-test
