bifrost:
  big-bang:
    type: public
    genesis-id: b_5AvcewD4kdzU2QTfgYDXJN1zcE4xrbqYR8hf8GVmQvx8
    source-path: https://raw.githubusercontent.com/Topl/Genesis_Testnets/update-during-epoch/openstack-test
