bifrost:
  big-bang:
    type: public
    genesis-id: b_Ed58mhKaR6VAWNTiWT3K33zdDJLrB4Cd2FsrnXxBuDc8
    source-path: https://raw.githubusercontent.com/Topl/Genesis_Testnets/7-staker-testnet/testnet1
