bifrost:
  big-bang:
    type: public
    genesis-id: b_DcG4Wes6DqcNqpJTKDg6Sfvcib8JTgZJ6QTHdJGz5DEd
    source-path: https://raw.githubusercontent.com/Topl/Genesis_Testnets/7-staker-testnet/testnet1
