bifrost:
  big-bang:
    type: public
    genesis-id: b_AeCx9Sc1xJyvyrsDTsYWKY4BGwCiuXRuCXNyQ5tyahMf
    source-path: https://raw.githubusercontent.com/Topl/Genesis_Testnets/BN-1269-migrate-public-testnet-to-testnet-topl-co/testnet2
